//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STOREEntities1 : DbContext
    {
        public STOREEntities1()
            : base("name=STOREEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Cart> tb_Cart { get; set; }
        public virtual DbSet<tb_CartDt> tb_CartDt { get; set; }
        public virtual DbSet<tb_Goods> tb_Goods { get; set; }
        public virtual DbSet<tb_Receipt> tb_Receipt { get; set; }
        public virtual DbSet<tb_ReceiptDt> tb_ReceiptDt { get; set; }
    }
}
