//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CartDt
    {
        public string CartId { get; set; }
        public string GoodId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual tb_Cart tb_Cart { get; set; }
        public virtual tb_Goods tb_Goods { get; set; }
    }
}
