//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Cart()
        {
            this.tb_CartDt = new HashSet<tb_CartDt>();
        }
    
        public string CartId { get; set; }
        public string Name { get; set; }
        public string Agency { get; set; }
        public string Status { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CartDt> tb_CartDt { get; set; }
    }
}
