//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Receipt()
        {
            this.tb_ReceiptDt = new HashSet<tb_ReceiptDt>();
        }
    
        public string ReceiptId { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ReceiptDt> tb_ReceiptDt { get; set; }
    }
}
